# page settings
title: Koki Yamaguchi's diary
author: Koki Yamaguchi
description: >-
  English language examined from a Japanese perspective

# url settings
domain: koki-yamaguchi.github.io
url: https://koki-yamaguchi.github.io
baseurl: ""

# profile settings
email: yk49at21@gmail.com
twitter_username: Ymgch_K

# plugins settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-github-metadata

# pagination settings
paginate: 10

collections:
  words:
    output: true

