# page settings
title: Koki Yamaguchi's diary
description: >-
  Exploring the world of English words.

# url settings
domain: koki-yamaguchi.github.io
url: https://koki-yamaguchi.github.io
baseurl: ""

# profile settings
email: yk49at21@gmail.com
twitter_username: Ymgch_K

# plugins settings
plugins:
  - jekyll-feed
  - jekyll-paginate

# pagination settings
paginate: 10

